### ISSUE TITLE
Help in Bitbucket pipeline script

### ISSUE THREAD

**Issue by wandersonveiga** [teambit/bit#1366]
Locally I can login into bit and download my components but when I tried to deploy my SPA in React by using Bitbucket pipeline to deploy my build to AWS S3 I got some problems. Please help me.

## Expected Behavior
Npm login - success
Bit login - success
Yarn install - success
. . . and so on

## Actual Behavior
Npm login - success

![npm](https://user-images.githubusercontent.com/11160008/50649389-e682f880-0f64-11e9-8271-ae53c91412f1.PNG)

Bit login - success? (just receive a message about analytics)
![analytics](https://user-images.githubusercontent.com/11160008/50649408-f39fe780-0f64-11e9-8139-51313f683a05.PNG)

Yarn install - failed
![yarn_error](https://user-images.githubusercontent.com/11160008/50649359-cf440b00-0f64-11e9-86ab-7efb2f9390f8.PNG)

## Steps to Reproduce the Problem

  My script is something like this:

```branches:
    staging:
      # Build-DEPLOY
      - step:
          script:
            - npm install bit-bin -g
            - bit config set user.name "myuser"
            - bit config set user.email myemail@hotmail.com
            - npm config set '@bit:registry' https://node.bitsrc.io
            - npx npm-cli-adduser
            - bit login --npmrc-path ./.npmrc
            - yarn install
            . . . 
```

## Specifications
I tried `npm-cli-adduser` as npm login client and use Pipeline variables into it. My `.npmrc` file has the configuration:
`@bit:registry=https://node.bitsrc.io//node.bitsrc.io/:_authToken={mytoken}`

**Comment by wandersonveiga** [comment]
Thanks!! Work just fine!!

**Comment by wandersonveiga** [comment]
This worked for public scope (without `bit login`) but in private scope `bit login`  with `--suppress-browser-launch` and `--skip-registry-config`  flags did not continue the pipeline, stuck to the phrase `Go to the following link in your browser::`

**Comment by itaymendel** [comment]
You don't have to run `bit login` in your CI.
Use a valid key and run `bit config set user.token <YOUR BIT TOKEN>`.

What do you try and do during CI? Install components using Yarn, or import them with Bit?
For yarn installation, you don't need bit-authentication. Only in `.npmrc`.

**Comment by itaymendel** [comment]
Awesome! Closing the issue :)

**Comment by kolin4** [comment]
hi im still facing similar prroblem.
My setup:
`.npmrc`
```
@XXX:registry=https://node.bit.cloud
@teambit:registry=https://node.bit.cloud
always-auth=true
```

pipe 
```
build: &build
  name: Build static files
  caches:
    - node
  script:
    - yarn global add bit-bin
    - yarn config set registry "@bit:registry = https://node.bitsrc.io"
    - yarn config set registry "@teambit:registry=https://node.bit.cloud"
    - yarn config set registry "@XXX:registry=https://node.bit.cloud"
    - echo "//node.bitsrc.io/:_authToken=$BIT_TOKEN" > .npmrc
    - bit config set analytics_reporting false
    - bit config set error_reporting false
    - bit config set user.token ${BIT_TOKEN}
    - yarn install
    - GATSBY_ACTIVE_ENV=development yarn build
  artifacts:
    - public/***

```

And im getting exact same `404 err` as OP.  I also tried with `npm` as a package manager but im getting same err. Could you share exact pipe setup for it?
