### ISSUE TITLE
Compile scss to css on `bit compile`

### ISSUE THREAD

**Issue by AlexandroPerez** [teambit/bit#4559]
### Description
When I `bit compile`, in node_modules `tsx` files get compiled to `js`, but `scss` files remain `scss` files. 

The issue is that when importing these components, it's going to be required to install **Sass** on that project, whether the project will uses sass or not. If the project is using it, is fine, but if not, the package will have to be installed just for the components.

### Describe the solution you'd like
If `scss` or `sass` files get compiled to `css` files, just like how `ts` or `tsx` files get compiled to `js`, then the component can be used on any project without the need to install **Sass**.

### Describe alternatives you've considered
Not using sass, or having the npm sass package as a dependency to the components.

**Comment by itaymendel** [comment]
This default behavior is by design.

We use tools like WebPack and Rollup to bundle a web application to a single target that contains all dependencies and assets. It is the application's responsibility to create runnable bundles for the browser. Components should only be compiled to a reusable target a bundler can consume. This process has several benfits:

* No bundled duplicate dependencies.
* No loss of data (CSS classes turned to hash).
* Enhances bundler features like tree-shaking and code splitting.

If we'd compile scss to css we loose a lot of information and hurt the consumer's bundler to be as effective as it can and will hurt performance (as different bundlers can use these styles to create vars, scoped classes, and other features). Moreover, it is very likely that you then end up with a lot of duplications in your bundle.

You can extend the compilation step to transpile scss to css, but I don't recommend it.

**Comment by AlexandroPerez** [comment]
@itaymendel I don't have much knowledge of tools like webpack, but maybe I didn't make my point clear? What I'd like bit to do in the `compile` process for `scss` is the same that is done for `ts` files: They're compiled to something that is ready for consumption. 

I also don't understand how there will be any loss of benefits from compiling a `scss` file into a `css` file. Probably, since I don't know how bundlers work, I may be wrong, but isn't the following compiling similar to what they do:

#### button.module.scss
```scss
.button {
  border-radius: 5px;
  height: 46px;
  text-align: center;

  &[data-variation="primary"] {
    color: white;
    background-color: #6c5ce7;
    border: 1px solid #6c5ce7;

    &:hover {
      border: 1px solid #6c5ce7;
      background-color: white;
      color: #6c5ce7;
    }
  }

  &[data-variation="secondary"] {
    border: 1px solid #6c5ce7;
    background-color: white;
    color: #6c5ce7;

    &:hover {
      border: 1px solid #6c5ce7;
      color: white;
      background-color: #6c5ce7;
    }
  }
}
```

#### transpiled/compiled to 
```css
.button {
  border-radius: 5px;
  height: 46px;
  text-align: center;
}
.button[data-variation="primary"] {
  color: white;
  background-color: #6c5ce7;
  border: 1px solid #6c5ce7;
}
.button[data-variation="primary"]:hover {
  border: 1px solid #6c5ce7;
  background-color: white;
  color: #6c5ce7;
}
.button[data-variation="secondary"] {
  border: 1px solid #6c5ce7;
  background-color: white;
  color: #6c5ce7;
}
.button[data-variation="secondary"]:hover {
  border: 1px solid #6c5ce7;
  color: white;
  background-color: #6c5ce7;
}
```

The above `css` is what I'd use if I didn't want to rely on `scss` features. So I really don't understand why, as a bit component developer, would have to force those who don't like SCSS to install it just to be able to use my component.

Also, if we're talking loss of benefits, I'd say compiling `ts` files into `js` also would apply to what you imply with `scss` to `css`, am I wrong? In such a case, why compile anything at all, typescript has a lot of benefits too. So why not simply ask those that will consume the components to install typescript as well.
