### ISSUE TITLE
unexpected styles leaking in overview page

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4815]
Sometimes, styles from the components apply to the docs at the overview page.
![Screen Shot 2021-08-26 at 20 29 42](https://user-images.githubusercontent.com/5400361/131022957-9bfd7397-554c-47f8-bb0c-03fa4304d248.png)

These generally come from 2 sources: global css, and env providers

## Global CSS leakage
We've written all our code to be overridable, so developers could reuse and customize our components.
This allows unscoped css rules to apply:

```css
body {
  font-family: sans-serif;
}

h2 {
  font-family: monospace;
  font-weight: bold;
  margin-bottom: 20px;
  font-size: 36px;
}

p {
  font-size: 20px;
}

a {
  color: green;
}

* {
  font-family: sans-serif;
}
```

This makes sense for applications - "we want the same look for all headers".
It makes partial sense for components - we'd like styles to be isolated, but it's not a requirement.

We can mitigate this by applying our own rules to these fundamental components. Something like:

```scss
  body .bitResets {
    background: white;
    margin: 0;
    /* ... */
  }

  .bitResetSection *, .bitResets {
    font-family: inherit;
    background: none;
    font-size: ?; // probably should apply on a per - component level
    letter-spacing: normal;
    /* ... */
  }

  // or apply to these tags:
  p, h1, h2, h3, h4, h5, h6, ul, ol, li, em, strong, table, tr, th, td, a { 
    &.bitResets {
      font-family: inherit;
      background: none;
      letter-spacing: normal;
      /* ... */
    }
  }
```

It's possible, since we have a relatively low number of components in the docs page.
We will have to increase the specificity of our styles, though.

## Providers
Using the env syntax, developers can add "providers" to the env, like so:

```tsx
const SomeTheme = {
  background: "#414141",
  color: "white",
  "--primaryColor": "blue",
};

export class SomeEnvPreview {
  static runtime = PreviewRuntime;
  static dependencies = [ReactAspect];

  static async provider([react]: [ReactPreview]) {
  react.registerProvider([props => <div {...props} style={SomeTheme} />]);
  return new SomeEnvPreview();
  }
}
```

This is a more component-oriented approach, and we really do want our theme in both the docs and compositions.

When the providers includes a theme, like background color, or even centering, it unexpectedly applies also to other parts of the page, like the docs section
This is by design - we allow developers to embed React components in the MDX, so we'd like to providers to be available there too.

You can see it at `docs-app/base.tsx`:

```tsx
// (simplified)
<Composer components={providers}>
  {/* ... */}
  <MDXLayout className={styles.mdx}>
  <Content />
  </MDXLayout>

  <CompositionsSummary compositions={compositions} />
  <ExamplesOverview examples={examples} />
  <Properties properties={docsModel.properties} />
</Composer>
```

We therefor need a more fine-grained API for this. Ideally, adding these two will add the flexibility needed:

Option 1 - Add a "target" or "context" field to the providers, telling them to work only in some use cases. We could also open a separate slot for the overview.

```tsx
react.registerProvider([
  { context: ['compositions'], use: props => <div {...props} style={CompositionsTheme} />
  { context: ['docs'], use: DocsThemeProvider />
]);
```

Option 2 - Create a "decorators" syntax, that will only apply to compositions, as suggested at #4692. It's extremely granular  and will provide a lot of value for developers.
