### ISSUE TITLE
Self hosted bit server can't render overview of components

### ISSUE THREAD

**Issue by YUFENGWANG** [teambit/bit#5437]
### Describe the bug

Self hosted bit server can't render overview of components

### Steps to Reproduce

1. docker pull bitcli/bit-server 
2. run with following config using docker-compose
```yaml
 version: "3"
services:
  bit-server:
    image: bitcli/bit-server:latest
    ports:
      - 3333:3000
    volumes:
      - ./data/weimai:/root/remote-scope  
      - ./logs:/root/Library/Caches/Bit/logs 
```
3. create a local workspace and add remote
4. bit export to remote 
5. components uploaded successfully, but the overview tab rendered failed

### Expected Behavior

overview tab rendered correctly

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/12859005/154901632-2d72b611-5309-4f01-bf50-737f883199b3.png)
![image](https://user-images.githubusercontent.com/12859005/154901668-04d1b924-be6d-4499-834c-ab535d333949.png)
```json
{"errors":[{"message":"Cannot query field \"elementsUrl\" on type \"Component\".","locations":[{"line":13,"column":9}]},{"message":"Cannot query field \"preview\" on type \"Component\".","locations":[{"line":19,"column":9}]}]}
```

### Specifications

- Bit version: lastest docker image
- Workspace type: local harmony
- Node version: local 16.13.0
- npm / yarn version: local yarn 1.22.17
- Platform: local mac

*for harmony workspace*
- relevant env  
- relevant aspects:  teambit.react/react

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

NO
