### ISSUE TITLE
Can't publish to private verdaccio npm registry

### ISSUE THREAD

**Issue by YUFENGWANG** [teambit/bit#5441]
### Describe the bug

I have set a local private verdaccio npm registry and follow the docs [link](https://github.com/teambit/bit/discussions/4707)
But when i run `bit tag --all`, It can't publish package to verdaccio

### Steps to Reproduce
1. run  verdaccio using docker
2. `npm adduser` to login to verdaccio and publish a test npm pkg to it successfully.
3. run bit-server
```yaml
version: "3"
services:
  bit-server:
    image: bitcli/bit-server:0.0.651
    ports:
      - 3333:3000
    volumes:
      - ./data/weimai:/root/remote-scope
      - ./logs:/root/Library/Caches/Bit/logs
```
4. add following config to workspace.jsonc
```jsonc
        "packageJson": {
          "publishConfig": {
            // "name": "@{scope}/{name}",
            "scope": "@weimai",
            "registry": "http://192.168.31.133:4873"
          }
        }
      }
```
5. run `bit tag --all`
6. got error 
![image](https://user-images.githubusercontent.com/12859005/154988510-97e30b93-82ed-4369-b6b0-039a5506858d.png)

### Expected Behavior

`bit tag --all` publish npm pkg to verdaccio successfully

### Specifications

- Bit version: local cli 0.0.655
- Workspace type: (harmony/legacy) harmony
- Node version: v16.9.1
- npm / yarn version: 7.21.1
- Platform: macos and docker 

*for harmony workspace*
- relevant env
- relevant aspects  `teambit.pkg/pkg` `teambit.react/react`

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):
