### ISSUE TITLE
Bit Quickstart Design Steps erroring out

### ISSUE THREAD

**Issue by Dave4272-Office** [teambit/bit#7541]
### Description

I am Following the steps in the bit quickstart for the design system but the bit new command is failing with the following error
![image](https://github.com/teambit/bit/assets/40066272/fa5eb020-0046-4dec-831d-c3fa4b1a2f4d)

### Specifications

- Bit version: 0.1.62
- Node version: 18.16.0
- npm / yarn version: 9.5.1
- Platform: Linux 6.3.5-2-MANJARO #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

Im using a clean environment (docker)

this is the compose file I am using to start the image and attaching the shell to work on it

```
name: node-bash
services:
  node:
    image: node:18.16.0
    container_name: nodejs
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.default.disable_ipv6: 0
    tty: true
    entrypoint: /usr/bin/bash
    volumes:
      - ./:/code:rw

networks:
  default:
    external: true
    name: local-infra-main-net

```
